---
title: "EDA"
output: github_document
---


```{r}
library(tidyverse)
```

## load the data

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## group by 
```{r}
weather_df%>%
  group_by(name,month)
```

## counting things

count month/name observations

```{r}
weather_df%>%
  group_by(name, month) %>%
  summarize(n_obs = n())
```

we can use count
```{r}
weather_df%>%
  count(name, month, name = "n_obs")
```

## never use base R's table!!!

```{r, eval=FALSE}
weather_df%>%
  pull(month)%>%
  table()
```

other helpful counters

```{r}
weather_df%>%
  group_by(month)%>%
  summarize(
    n_obs = n(),
    n_days = n_distinct(date)
  )
```

